import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const opensans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Lead School Assigemnt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
